In [1]:
import pandas as pd

In [2]:
from system_check import *
CUDA_state_print_limited()

CUDA доступна: True
Количество GPU: 4

In [6]:
df_full = pd.read_csv('/home/pmartynyuk/UnTIE project/datasets/ruserrc_structured.csv', encoding='utf-8', sep=';')
df_full

,id,text,Conс_aspects,Conс_count,Use_aspects,Use_count,Tool_aspects,Tool_count,Method_aspects,Method_count,...,Conc_count,Example_aspects,Example_count,Task_aspects,Task_count,Goal_aspects,Goal_count,Adv_aspects,Adv_count,text_clean
0,2019-17-1-1,В рамках проекта по <Task> автоматизации раб...,[],0,['упрощение исследований поэтических текстов'],1,[],0,[],0,...,0,[],0,['автоматизации работы с поэтическими текстами...,2,[],0,[],0,В рамках проекта по автоматизации работы с ...
1,2019-17-1-2,На основании обобщенного <Method> алгоритма ...,[],0,['затруднить стороннему наблюдателю выявление ...,3,[],0,['алгоритма защищенного информационного обмена'],1,...,0,[],0,[],0,[],0,[],0,На основании обобщенного алгоритма защищенн...
2,2019-17-1-3,Проблема <Task> своевременного предупреждения...,[],0,['рассчитывать параметры цунами у защищаемой б...,1,[],0,[],0,...,0,[],0,['своевременного предупреждения населения об о...,2,['объединение существующих реализаций алгоритм...,1,[],0,Проблема своевременного предупреждения насел...
3,2019-17-1-4,На фоне множества методов проведения геофизиче...,[],0,[],0,[],0,"['функции сглаживания', 'B-сплайн', 'B-сплайна']",3,...,1,[],0,[],0,[],0,[],0,На фоне множества методов проведения геофизиче...
4,2019-17-1-5,<Contrib> Представлен способ получения видеод...,[],0,['оперативно начать видеотрансляцию в облачные...,2,['шаблона проектирования MVC'],1,[],0,...,0,[],0,[],0,[],0,['быстро и надежно фиксировать события'],1,Представлен способ получения видеодоказатель...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
586,1611,<Contrib> Приведена общая схема взаимодейств...,[],0,[],0,['объектно-ориентированных средств программиро...,1,[],0,...,0,[],0,[],0,[],0,[],0,Приведена общая схема взаимодействия аппара...
587,1614,<Contrib> Предлагается решение задачи <Task...,[],0,[],0,[],0,['метод использования виртуального посредничес...,1,...,0,['сфера туризма'],1,[],0,[],0,['позволяющие обеспечить требуемый характер ко...,2,Предлагается решение задачи организации ...
588,1615,В статье <Contrib> рассматриваются проблемы ...,[],0,[],0,[],0,['методов множественной регрессии'],1,...,0,[],0,[],0,[],0,[],0,В статье рассматриваются проблемы прогнозир...
589,1616,В статье <Contrib> рассматривается моделиров...,[],0,[],0,[],0,['аппарат двойственных оценок'],1,...,0,['анализа возможности по пропуску газа действу...,1,[],0,[],0,[],0,В статье рассматривается моделирование сцен...
590,1617,В статье <Contrib> предлагается решение зада...,[],0,[],0,"['ПО MS SharePoint', 'Power web-part', 'Advanc...",4,[],0,...,0,['моделирования пользовательской среды пакета ...,1,[],0,[],0,[],0,В статье предлагается решение задачи пос...

In [10]:
df_task_filtered = df_full[df_full['Task_count'] > 0].reset_index(drop=True)
columns = ["text", "Task_aspects", "Task_count", "text_clean"]
df_task_filtered = df_task_filtered[columns]
df_task_filtered

,text,Task_aspects,Task_count,text_clean
0,В рамках проекта по <Task> автоматизации раб...,['автоматизации работы с поэтическими текстами...,2,В рамках проекта по автоматизации работы с ...
1,Проблема <Task> своевременного предупреждения...,['своевременного предупреждения населения об о...,2,Проблема своевременного предупреждения насел...
2,Работа посвящена <Contrib> описанию структур...,['генотипирования вируса клещевого энцефалита ...,2,Работа посвящена описанию структуры информа...
3,Для эффективного <Task> освоения залежей угл...,['освоения залежей углеводородов'],1,Для эффективного освоения залежей углеводор...
4,При <Task> формировании единого информационно...,['формировании единого информационного простра...,1,При формировании единого информационного про...
...,...,...,...,...
163,Рассматриваются проблемы <Task> проектирован...,['проектирования интеллектуальных систем управ...,1,Рассматриваются проблемы проектирования инт...
164,"Планирование землепользования , охрана окружаю...",['поддержки принятия решений'],1,"Планирование землепользования , охрана окружаю..."
165,Во многих <Task> задачах текстовой классифик...,['задачах текстовой классификации'],1,Во многих задачах текстовой классификации ...
166,<Task> Выбор оптимального расположения логис...,['Выбор оптимального расположения логистически...,2,Выбор оптимального расположения логистическ...
167,Рассматривается задача <Task> кластеризации ...,['кластеризации интернет-ресурсов'],1,Рассматривается задача кластеризации интерн...

In [11]:
# Сохранение в CSV
df_task_filtered.to_csv(
    '/home/pmartynyuk/UnTIE project/datasets/ruserrc_task.csv',
    encoding='utf-8-sig',    # UTF-8 с BOM (открывается в Excel без кракозябр)
    sep=';',                 # Точка с запятой (стандарт для RU-locale)
    index=False,             # Не сохранять индексы строк
    header=True              # Сохранить заголовки колонок
)